name: surrah
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.0
  get_it: ^9.2.1
  flutter_svg: ^2.3.0
  flutter_dotenv: ^6.0.1
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.16.0
  flutter_screenutil: ^5.7.0
  smooth_page_indicator: ^1.2.1
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  rename: ^3.1.0
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - .env

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
        - asset: assets/fonts/cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/cairo/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/cairo/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/cairo/Cairo-Black.ttf
          weight: 900

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true

  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#123C36"
  image_path: "assets/images/appLogo.png"

flutter_native_splash:
  color: "#123C36"
  image: assets/images/splashLogo.png
  android: true
  ios: true
  web: false
  android_12:
    color: "#123C36"
    image: assets/images/splashLogo.png
  fullscreen: true

flutter_intl:
  enabled: true
